### ISSUE TITLE
template matching link

### ISSUE THREAD

**Issue by McHaillet** [phonchi/Computational-CryoET#1]
Hi Phonchi!

Could you link to my python package (https://github.com/SBC-Utrecht/pytom-match-pick) with the 'Extensive angular sampling ...' (pytom) paper. This is my much easier-to-integrate package with improved performance that has spun-off from pytom. So I would recommend that over the old repo.

Just trying to make sure people are directed to it as all my recent effort for particle picking been there instead of the pytom repo. Would be much appreciated!

Best wishes,
Marten

**Comment by phonchi** [comment]
Dear Marten:

Thanks for the heads up! I’ve updated the link to your new package, [pytom-match-pick](https://github.com/SBC-Utrecht/pytom-match-pick). It’s great to see your efforts on this great tool!
