### ISSUE TITLE
Adding CCP-EM tools

### ISSUE THREAD

**Issue by shruthivis** [phonchi/Computational-CryoET#2]
Hi 
Thanks for your wonderful compilation. Can you add the highly usable CCP-EM/Rosalind Franklin Institute tools to your list?
For e.g. for de-noising: https://gitlab.com/ccpem/ccpem-denoiser 
for simulating tomograms: https://rosalindfranklininstitute.github.io/parakeet/ 

Thanks
Shruthi

**Comment by phonchi** [comment]
Dear Shruthi,

Thank you for your kind words and for sharing these valuable tools. I have added the CCP-EM Denoiser ([ccpem-denoiser](https://gitlab.com/ccpem/ccpem-denoiser)) and Parakeet for simulating tomograms ([Parakeet](https://rosalindfranklininstitute.github.io/parakeet/)) to the compilation.

I appreciate your contribution! If you have any more suggestions or feedback, please feel free to reach out.
